//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod app_template;

pub mod organization;
pub mod permission;
pub mod schedule;
pub mod user;

pub mod log_api_operation;
pub mod log_system;
pub mod log_user_login;
pub mod log_web;

pub mod sys_config;
pub mod sys_dict_data;
pub mod sys_dict_dimension;
pub mod sys_image_captcha;
pub mod sys_image_resource;
