//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod app_template;

pub mod log_api_operation;
pub mod log_system;
pub mod log_user_login;
pub mod log_web;
pub mod perm_department;
pub mod perm_department_role_rel;
pub mod perm_menu;
pub mod perm_menu_role_rel;
pub mod perm_openapi;
pub mod perm_openapi_role_rel;
pub mod perm_role;
pub mod perm_token;
pub mod perm_token_role_rel;
pub mod schedule_job;
pub mod schedule_job_event_log;
pub mod schedule_job_status_log;
pub mod sys_config;
pub mod sys_dict_data;
pub mod sys_dict_dimension;
pub mod sys_image_captcha;
pub mod sys_image_resource;
pub mod user_base;
pub mod user_email;
pub mod user_phone;
pub mod user_role_rel;
