//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod app_template;

pub mod api_http;
pub mod api_role_http_rel;
pub mod api_token;
pub mod log_http;
pub mod log_system;
pub mod log_web;
pub mod perm_menu;
pub mod perm_role;
pub mod perm_role_menu_rel;
pub mod perm_user;
pub mod perm_user_token;
pub mod perm_role_user_rel;
pub mod sys_captcha;
pub mod sys_config;
pub mod sys_icon;
pub mod log_user_login;
