//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::app_template::Entity as AppTemplate;

pub use super::log_api_operation::Entity as LogApiOperation;
pub use super::log_system::Entity as LogSystem;
pub use super::log_user_login::Entity as LogUserLogin;
pub use super::log_web::Entity as LogWeb;
pub use super::sys_config::Entity as SysConfig;
pub use super::sys_dict_data::Entity as SysDictData;
pub use super::sys_dict_dimension::Entity as SysDictDimension;
pub use super::sys_image_captcha::Entity as SysImageCaptcha;
pub use super::sys_image_resource::Entity as SysImageResource;
