//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::app_template::Entity as AppTemplate;

pub use super::log_api_operation::Entity as LogApiOperation;
pub use super::log_system::Entity as LogSystem;
pub use super::log_user_login::Entity as LogUserLogin;
pub use super::log_web::Entity as LogWeb;
pub use super::perm_department::Entity as PermDepartment;
pub use super::perm_department_role_rel::Entity as PermDepartmentRoleRel;
pub use super::perm_menu::Entity as PermMenu;
pub use super::perm_menu_role_rel::Entity as PermMenuRoleRel;
pub use super::perm_openapi::Entity as PermOpenapi;
pub use super::perm_openapi_role_rel::Entity as PermOpenapiRoleRel;
pub use super::perm_role::Entity as PermRole;
pub use super::perm_token::Entity as PermToken;
pub use super::perm_token_role_rel::Entity as PermTokenRoleRel;
pub use super::perm_user_email::Entity as PermUserEmail;
pub use super::perm_user_phone::Entity as PermUserPhone;
pub use super::perm_user_role_rel::Entity as PermUserRoleRel;
pub use super::schedule_job::Entity as ScheduleJob;
pub use super::schedule_job_event_log::Entity as ScheduleJobEventLog;
pub use super::schedule_job_status_log::Entity as ScheduleJobStatusLog;
pub use super::sys_captcha::Entity as SysCaptcha;
pub use super::sys_config::Entity as SysConfig;
pub use super::sys_dict_data::Entity as SysDictData;
pub use super::sys_dict_dim::Entity as SysDictDim;
pub use super::sys_image::Entity as SysImage;
pub use super::user_base::Entity as UserBase;
