[workspace]
resolver = "2"
members = [
    # 数据库
    "core/entity",
    "core/migration",
    "core/dao",
    # 通用组件
    "core/code",
    "core/config",
    "core/logger",
    "core/response",
    "core/database",
    "core/utils",
    # 业务
    "core/dto",
    "core/service",
    # App
    "app/web",
]
default-members = ["app/web"]
