[workspace]
resolver = "2"
members = [
    # 通用组件
    "core/code",
    "core/config",
    # "core/logger",
    "core/response",
    "core/database",
    "core/utils",
    # 数据库
    "core/entity",
    "core/migration",
    # App
    "app/web",
]
default-members = ["app/web"]
