[workspace]
resolver = "2"
members = [
    "code",
    "code_msg_derive",
    "database",
    "entity",
    "logger",
    "migration",
    "response",
    "context",
    "actix_validator",
    "utils",
    "jwt",
]
