[package]
name = "code_msg_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true # 开启过程宏

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
