[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
utils = { path = "../utils" }

sea-orm = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
chrono = { workspace = true }
