//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "log_http")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Option<i32>,
    pub nickname: Option<String>,
    pub trace_id: Option<String>,
    pub status_code: i32,
    pub method: String,
    pub path: String,
    pub query: Option<String>,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")", nullable)]
    pub body: Option<String>,
    pub remote_addr: String,
    pub user_agent: String,
    pub cost: i32,
    pub htpp_type: String,
    pub note: Option<String>,
    pub created_at: DateTimeLocal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
