//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "log_system")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip)]
    pub id: i32,
    /// 用户ID
    pub user_id: Option<i32>,
    /// 用户昵称
    pub nickname: Option<String>,

    /// 日志记录器名称
    #[serde(default)]
    pub name: String,
    /// Span Id
    #[serde(default)]
    pub span_id: Option<u32>,
    /// 模块路径
    #[serde(default)]
    pub module_path: Option<String>,
    /// 描述发生此元数据所描述的跨度或事件的系统部分
    #[serde(default)]
    pub target: String,
    /// 文件
    #[serde(default)]
    pub file: Option<String>,
    /// 报错行数
    #[serde(default)]
    pub line: Option<u32>,
    /// 日志级别
    #[serde(default)]
    pub level: String,
    /// 事件类型
    #[serde(default)]
    pub kind: String,
    /// 是否为事件
    /// serialize_with = "i8_to_bool"
    #[serde(default)]
    pub is_event: bool,
    /// 是否为 span
    #[serde(default)]
    pub is_span: bool,
    /// 日志字段名称列表
    #[serde(default)]
    pub fields: Option<String>,
    /// fields 日志数据集
    #[sea_orm(column_type = "Text", nullable)]
    pub field_data: Option<String>,
    /// 日志信息
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,

    /// 业务码
    pub code: Option<i32>,
    /// 业务码信息
    pub code_msg: Option<String>,
    /// 堆栈信息
    #[sea_orm(column_type = "Text", nullable)]
    pub stack: Option<String>,

    /// 备注
    pub note: Option<String>,
    /// 创建时间
    #[serde(skip)]
    pub created_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
